In [1]:
import numpy as np
# 生成原始范围数组（0到2986）
low, high = 0, 3540
original = np.arange(low, high)

In [2]:
# 生成不重复的随机数组并排序（示例）
sample_size = 540
np_random_unique = np.random.choice(original, size=sample_size, replace=False)
sorted_array = np.sort(np_random_unique)

In [3]:
sorted_array.shape

(540,)

In [4]:
sorted_array

array([   1,    5,    8,   15,   19,   21,   30,   31,   34,   38,   42,
         45,   47,   48,   58,   61,   68,   69,   72,   77,   88,   96,
         97,   99,  118,  127,  129,  154,  158,  160,  167,  176,  188,
        190,  199,  201,  213,  214,  215,  228,  235,  260,  261,  267,
        270,  271,  276,  289,  295,  299,  306,  319,  327,  330,  335,
        341,  348,  350,  355,  356,  360,  379,  387,  388,  400,  405,
        406,  429,  436,  440,  451,  452,  453,  470,  474,  477,  482,
        483,  490,  507,  512,  519,  536,  545,  550,  560,  561,  564,
        567,  573,  575,  589,  592,  595,  600,  620,  627,  632,  636,
        637,  641,  643,  646,  652,  655,  660,  662,  668,  675,  677,
        690,  707,  709,  714,  716,  721,  726,  727,  741,  748,  749,
        752,  754,  757,  759,  763,  766,  771,  777,  785,  793,  794,
        825,  826,  828,  839,  840,  846,  862,  876,  893,  898,  903,
        904,  910,  928,  929,  938,  946,  949,  962,  965,  966,  972,
        973,  981,  997,  998, 1022, 1038, 1059, 1062, 1066, 1068, 1070,
       1075, 1083, 1086, 1087, 1093, 1097, 1107, 1118, 1127, 1131, 1148,
       1150, 1157, 1160, 1171, 1178, 1182, 1194, 1196, 1203, 1212, 1219,
       1224, 1228, 1231, 1238, 1246, 1247, 1258, 1260, 1263, 1276, 1279,
       1282, 1289, 1290, 1303, 1306, 1310, 1313, 1317, 1323, 1328, 1330,
       1331, 1336, 1350, 1359, 1361, 1364, 1365, 1373, 1384, 1392, 1404,
       1405, 1414, 1416, 1420, 1425, 1454, 1459, 1477, 1479, 1484, 1489,
       1491, 1497, 1500, 1504, 1508, 1513, 1517, 1521, 1530, 1533, 1538,
       1539, 1541, 1547, 1548, 1553, 1555, 1579, 1581, 1586, 1588, 1590,
       1593, 1596, 1598, 1601, 1607, 1616, 1636, 1658, 1665, 1676, 1679,
       1683, 1695, 1704, 1715, 1718, 1724, 1742, 1745, 1747, 1753, 1767,
       1783, 1789, 1792, 1798, 1804, 1808, 1812, 1828, 1829, 1833, 1841,
       1849, 1853, 1855, 1882, 1885, 1899, 1903, 1908, 1912, 1919, 1922,
       1931, 1948, 1954, 1958, 1961, 1966, 1983, 1994, 2005, 2029, 2031,
       2032, 2036, 2037, 2038, 2043, 2056, 2059, 2064, 2067, 2076, 2088,
       2090, 2093, 2107, 2113, 2121, 2125, 2130, 2132, 2136, 2162, 2174,
       2196, 2200, 2202, 2215, 2216, 2235, 2238, 2239, 2244, 2257, 2263,
       2269, 2274, 2277, 2284, 2289, 2292, 2294, 2296, 2299, 2303, 2337,
       2342, 2343, 2347, 2350, 2354, 2361, 2362, 2368, 2373, 2375, 2383,
       2386, 2394, 2396, 2424, 2427, 2443, 2444, 2449, 2451, 2469, 2475,
       2476, 2480, 2485, 2491, 2497, 2499, 2523, 2533, 2540, 2556, 2562,
       2571, 2577, 2586, 2591, 2593, 2594, 2597, 2603, 2607, 2608, 2612,
       2616, 2631, 2636, 2640, 2647, 2649, 2652, 2655, 2661, 2682, 2688,
       2724, 2725, 2729, 2745, 2751, 2755, 2756, 2767, 2776, 2778, 2790,
       2803, 2804, 2819, 2829, 2838, 2841, 2842, 2850, 2851, 2858, 2865,
       2868, 2871, 2875, 2878, 2891, 2896, 2899, 2906, 2910, 2914, 2915,
       2934, 2935, 2943, 2951, 2957, 2965, 2969, 2973, 2976, 2981, 2986,
       2993, 2998, 3003, 3022, 3031, 3033, 3035, 3037, 3047, 3050, 3051,
       3052, 3053, 3054, 3065, 3078, 3081, 3085, 3104, 3115, 3118, 3120,
       3122, 3130, 3133, 3141, 3143, 3150, 3153, 3161, 3166, 3169, 3179,
       3180, 3181, 3185, 3195, 3198, 3207, 3211, 3212, 3234, 3241, 3252,
       3260, 3262, 3266, 3276, 3283, 3285, 3296, 3297, 3304, 3316, 3317,
       3319, 3329, 3330, 3335, 3337, 3339, 3340, 3343, 3351, 3353, 3356,
       3360, 3365, 3375, 3384, 3397, 3411, 3414, 3415, 3416, 3421, 3424,
       3434, 3441, 3446, 3449, 3458, 3466, 3477, 3484, 3501, 3509, 3515,
       3517])

In [5]:
# 找出原始范围中存在但排序数组中缺失的数字，并反向排列
missing_numbers = np.setdiff1d(original, sorted_array)  # 差集（默认升序）
# reverse_missing = missing_numbers[::-1]  # 反转实现降序

In [6]:
missing_numbers

array([   0,    2,    3, ..., 3537, 3538, 3539])

In [7]:
missing_numbers.shape

(3000,)

In [8]:
# -----------------------------------------------------------------
# 保存为txt文件
# -----------------------------------------------------------------
# 保存 sorted_array（格式：每行一个数字）
np.savetxt('E:\QCL\Test.txt', missing_numbers, fmt='%d', delimiter='\n')

# 保存 reverse_missing（格式：每行一个数字）
np.savetxt('E:\QCL\Val.txt', sorted_array, fmt='%d', delimiter='\n')